// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/woojae9488/slack-test-bot/config"
	"github.com/woojae9488/slack-test-bot/handler"
	"github.com/woojae9488/slack-test-bot/slack"
)

// Injectors from wire.go:

func initializeApp() App {
	serverConfig := config.NewServerConfig()
	slackConfig := config.NewSlackConfig(serverConfig)
	configConfig := config.NewConfig(serverConfig, slackConfig)
	eventService := slack.NewEventService(configConfig)
	slackHandler := handler.NewSlackHandler(eventService)
	errorHandler := handler.NewErrorHandler()
	app := NewApp(slackHandler, errorHandler)
	return app
}
